/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Windows;

import Classe.Arbres;
import Classe.Pint;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author fredy_000
 */
public class WindowsArc extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */  
      Pint pint ;
      Arbres arbres ;
      Frame frame1;
    public WindowsArc(Arbres arbole,Pint pinta ,int I,Frame frame){
       this.pint =pinta;
       this.arbres=arbole;
       this.i=I;
       frame1 = frame;
        
        initComponents();
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        tm = new javax.swing.JTextField();

        setTitle("Arc");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setText("Entrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 150, 90, 23);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nouveau arc"));
        panel.setLayout(null);

        jLabel3.setText("Longueur");
        panel.add(jLabel3);
        jLabel3.setBounds(10, 80, 100, 14);

        jLabel2.setText("Dernier noeud");
        panel.add(jLabel2);
        jLabel2.setBounds(10, 50, 90, 14);

        jLabel1.setText("Premier noeud");
        panel.add(jLabel1);
        jLabel1.setBounds(10, 20, 90, 14);

        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        n1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                n1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                n1KeyReleased(evt);
            }
        });
        panel.add(n1);
        n1.setBounds(100, 20, 30, 20);

        n2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                n2KeyReleased(evt);
            }
        });
        panel.add(n2);
        n2.setBounds(100, 50, 30, 20);

        tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmActionPerformed(evt);
            }
        });
        tm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tmKeyReleased(evt);
            }
        });
        panel.add(tm);
        tm.setBounds(100, 80, 30, 20);

        getContentPane().add(panel);
        panel.setBounds(10, 20, 160, 120);

        setBounds(60, 150, 190, 231);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int x;int y;int ta;
         if(n1.getText().length()<1 || n2.getText().length()<1 ||tm.getText().length()<1)
           JOptionPane.showMessageDialog(null,"Erreur .. Données manquantes : ");
         else{
           x=Integer.parseInt(n1.getText());
           y=Integer.parseInt(n2.getText());
           ta=Integer.parseInt(tm.getText());         
     
         if(x==y)
           JOptionPane.showMessageDialog(null,"Erreur.. Vous devez taper un autre noeud : "+y);
         else if(x<0 || x>=i || y<0 || y>=i){
            JOptionPane.showMessageDialog(null,"Erreur.. Noeud non validé "); 
         }else{
             arbres.setAdjacence(x, y, 1);
             arbres.setAdjacence(y, x, 1);
             arbres.setCoefficient(x, y, ta);
             arbres.setCoefficient(y, x, ta);
             n1.setText(null);
             n2.setText(null);
             tm.setText(null);
            Pint.pintLigne(WindowsPrincipal.jPanel1.getGraphics(),arbres.getCordeX(x), arbres.getCordeY(x), arbres.getCordeX(y), arbres.getCordeY(y), ta);
            
         } 
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void n1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n1KeyReleased
     String tem = new String(n1.getText());
       StringBuffer tem2= new StringBuffer();       
        for (int j = 0; j < tem.length(); j++) {          
            if(Character.isDigit(tem.charAt(j))){                
             tem2.append(tem.charAt(j));
            } 
        }
        n1.setText(""+tem2);  
    }//GEN-LAST:event_n1KeyReleased

    private void n1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1KeyPressed

    private void n2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n2KeyReleased
      String tem = new String(n2.getText());
       StringBuffer tem2= new StringBuffer();       
        for (int j = 0; j < tem.length(); j++) {          
            if(Character.isDigit(tem.charAt(j))){                
             tem2.append(tem.charAt(j));
            } 
        }
        n2.setText(""+tem2);        // TODO add your handling code here:
    }//GEN-LAST:event_n2KeyReleased

    private void tmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmKeyReleased
       String tem = new String(tm.getText());
       StringBuffer tem2= new StringBuffer();       
        for (int j = 0; j < tem.length(); j++) {          
            if(Character.isDigit(tem.charAt(j))){                
             tem2.append(tem.charAt(j));
            } 
        }
        tm.setText(""+tem2); // TODO add your handling code here:
    }//GEN-LAST:event_tmKeyReleased

    private void tmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
           // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frame1.setEnabled(true); // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowsArc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowsArc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowsArc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowsArc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new WindowsArc().setVisible(true);
            }
        });
    }
private int i=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tm;
    // End of variables declaration//GEN-END:variables
}
